export const LIBRARY_PREFS_KEY = "asoprs-library-preferences";

export type ViewMode = "category" | "alpha";
export type LayoutMode = "grouped" | "dense";
export type SortMode = "title" | "category" | "pages" | "asoprs";

export const ASOPRS_INDEX_PATTERNS = [
  "Acquired Laxity",
  "Blepharochalasis",
  "Floppy Eyelid",
  "Horizontal Eyelid Tightening",
  "Lateral and Medial Canthoplasty",
  "Lower Eyelid Blepharoplasty",
  "Periorbital Hollows",
  "Upper Eyelid Blepharoplasty",
  "Aponeurotic Ptosis",
  "Myogenic Ptosis",
  "External (Transcutaneous) Levator Advancement",
  "Frontalis Suspension",
  "Internal (Transconjunctival) Levator-Mullers Muscle Resection",
  "Marcus Gunn Jaw-Winking Syndrome",
  "Eyelid Pediatric Ptosis",
  "Traumatic Ptosis",
  "Brow Lift",
  "Cicatricial Entropion",
  "Congenital Entropion",
  "Epiblepharon",
  "Involutional or Senile Entropion",
  "Ocular Cicatricial Pemphigoid, Drug-Induced Pemphigoid, and Stevens-Johnson Syndrome",
  "Spastic Entropion",
  "Trachoma",
  "Trichiasis",
  "Reconstructing Large Defects Involving Forehead, Cheeks",
  "Reconstruction of Lower Eyelid Defects Involving the Margin",
  "Reconstruction of Medial and Lateral Canthal Defects",
  "Mohs Micrographic Surgery",
  "Periocular Burns",
  "Upper Eyelid Reconstruction Involving Eyelid Margin",
  "Eyelid Retraction",
  "Acne Rosacea",
  "Blepharitis, Meibomitis, and Hordeola",
  "Eyelid Degenerative and Inflammatory Disorders",
  "Eyelid edema",
  "Milia",
  "Chronic plaque psoriasis",
  "Spontaneous urticaria and angioedema",
  "Vitiligo",
  "Erysipelas",
  "Periorbital Herpes Zoster",
  "Molluscum Contagiosum",
  "Periocular Herpes simplex virus (HSV)",
  "Generalized staphylococcal scalded skin syndrome",
  "Tinea faciei",
  "Benign Melanotic Skin Lesions",
  "Benign Eyelid Neoplasia",
  "Conjunctival Epithelial Malignancies",
  "Conjunctival Melanoma",
  "Actinic Keratosis",
  "Basal Cell Carcinoma",
  "Basal Cell Nevus Syndrome (Gorlin-Goltz Syndrome)",
  "Keratoacanthoma of the Eyelid",
  "Squamous Cell Carcinoma of the Eyelid",
  "Lentigo Maligna, Lentigo Maligna Melanoma, and Melanocytic Hyperplasia",
  "Merkel Cell Carcinoma",
  "Microcystic Adnexal Carcinoma",
  "Sebaceous Adenocarcinoma",
  "Anatomy of the External Ear",
  "Facial implants",
  "Necklift (Platysmaplasty)",
  "Otoplasty and Earlobe Surgery",
  "Rhinoplasty",
  "Rhytidectomy (Facelift)",
  "Botulinum Toxin in Facial Aesthetics",
  "Chemical Peels",
  "Soft-Tissue Fillers",
  "Lasers and Energy-Based Treatments for Cosmetic Improvement and Skin Rejuvenation",
  "Benign Essential Blepharospasm",
  "Facial Nerve Palsy",
  "Giant Cell Arteritis and Temporal Artery Biopsy",
  "Hemifacial Spasm",
  "Horner Syndrome",
  "Idiopathic Intracranial Hypertension",
  "Melkersson-Rosenthal Syndrome",
  "Myasthenia Gravis",
  "CDCR with Jones Tube",
  "Congenital Lacrimal Dysgenesis",
  "Canalicular Infections and Inflammation",
  "Canalicular Obstruction",
  "Acquired Nasolacrimal Duct Obstruction",
  "Congenital Nasolacrimal Duct Obstruction (NLDO)",
  "Dacryocystocele (amniotocele)",
  "Dacryocystectomy",
  "Ectrodactyly-ectodermal dysplasia-cleft syndrome (EEC Syndrome)",
  "Endoscopic, Endonasal, or Transnasal Dacryocystorhinostomy (EndoDCR)",
  "Diagnostic Techniques to Evaluate Obstructive or Reflexive Epiphora",
  "Paranasal Sinus Anatomy and Physiology",
  "Silicone Intubation of Nasolacrimal Drainage System",
  "History and Examination for Orbital Pathology",
  "Corneal Neurotization",
  "The Challenging Anophthalmic Socket",
  "Enucleation and Evisceration",
  "Eosinophilic orbital disease",
  "Granulomatosis with Polyangiitis (Wegener’s Granulomatosis)",
  "Idiopathic Orbital Inflammation",
  "IgG4-Related Disease",
  "Orbital and Ocular Adnexal Sarcoidosis",
  "Adult Orbital Xanthogranulomatous Disease",
  "Adenoid Cystic Carcinoma of the Lacrimal Gland",
  "Dacryops",
  "Malignant Mixed Tumor of the Lacrimal Gland",
  "Pleomorphic adenoma",
  "Optic Nerve Sheath Meningioma",
  "Schwannoma (Neurilemoma)",
  "Spheno-Orbital Meningioma (Sphenoid Wing Meningioma)",
  "Anophthalmos, Microphthalmos, and Congenital Socket Malformations",
  "Craniosynostosis Syndromes",
  "Dermoid Cysts",
  "Dermolipoma",
  "Genetics for the Oculofacial and Orbital Surgeon",
  "Orbital Meningocele, Encephalocele, and Meningoencephalocele",
  "Intraorbital Foreign Bodies",
  "Late Post-Traumatic Enophthalmos",
  "Le Fort Fractures",
  "Mandible Fractures",
  "Medial Orbital Wall Fractures",
  "Newer Orbital Implants",
  "Naso-Orbital Ethmoid Fractures",
  "Orbital Floor Fractures",
  "Orbital Hemorrhage",
  "Orbital Apex and Roof Fractures",
  "Sinus Mucocele",
  "Zygomatic maxillary complex (ZMC) fractures",
  "Fibrous Histiocytoma",
  "Orbital Rhabdomyosarcoma",
  "Uncommon Orbital Lesions- Solitary Fibrous Tumors",
  "Allergic Fungal Sinusitis",
  "Aspergillosis",
  "Phycomycosis (Zygomycosis, Mucormycosis)",
  "Bacterial Orbital Cellulitis",
  "Methicillin-Resistant Staphylococcus Aureus (MRSA)",
  "Necrotizing Fasciitis",
  "Palpebral Orbital Ophthalmomyiasis",
  "The Enophthalmos Syndromes",
  "Repair of Traumatic Telecanthus",
  "Ocular Adnexal Follicular Lymphoma",
  "Ocular Adnexal MALT Lymphoma",
  "Mantle Cell Lymphoma",
  "Metastatic Tumors of the Orbit",
  "Plasma Cell Tumors of the Orbit and Periocular Region",
  "Rosai-Dorfman Disease",
  "Endoscopic orbital surgery",
  "Surgical Approaches to the Orbit",
  "Nonsurgical Management of Thyroid Eye Disease",
  "Orbital Decompression in Thyroid Eye Disease",
  "Pathogenesis of Thyroid Eye Disease",
  "Cavernous Malformation",
  "Carotid Cavernous Sinus Fistula",
  "Infantile Hemangioma",
  "Lymphangioma",
  "Orbital varix",
  "Artificial Intelligence in Ophthalmic Plastic and Reconstructive Surgery",
  "Environmental Sustainability in Ophthalmic Plastic and Reconstructive Surgery",
].map((pattern) => pattern.toLowerCase());

export function getAsoprsSortIndex(title: string) {
  const normalized = title.toLowerCase();
  const index = ASOPRS_INDEX_PATTERNS.findIndex(
    (pattern) => normalized.includes(pattern) || pattern.includes(normalized)
  );
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}
