# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "study-portal"

[db]
major_version = 17

[db.migrations]
enabled = true
schema_paths = ["./migrations/*.sql"]

[auth]
enabled = true
site_url = "https://study-portal-hazel.vercel.app"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://127.0.0.1:3000/auth/callback",
  "https://study-portal-hazel.vercel.app/auth/callback",
  "https://study-portal-miguel-sanchezgrices-projects.vercel.app/auth/callback",
  "https://study-portal-enetzbyzu-miguel-sanchezgrices-projects.vercel.app/auth/callback",
]
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 12
password_requirements = "lower_upper_letters_digits_symbols"

[auth.rate_limit]
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
secure_password_change = true
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
